customhost = "database-1.c1h3q8wr0qzi.us-west-1.rds.amazonaws.com"
customuser = "admin"
custompass = "12345678"
customdb = "database-1"
custombucket = "abhiprojectbuc"
customregion = "us-west-1"
